@startuml

state ready as "Ready"
state parsingScheme as "Parsing Scheme"
state waitingShortScheme as "Waiting Short Scheme"
state detectingShortScheme as "Detecting Short Scheme"
state waitingLongScheme as "Waiting Long Scheme"
state loggingDetected as "Logging Option Detected"
state authDetected as "Authorization Option Detected"

[*] --> ready
ready --> ready: accept(" ")
ready --> waitingShortScheme: accept("-")
waitingShortScheme --> waitingLongScheme: accept("-")
waitingShortScheme --> loggingDetected: accept("l")
loggingDetected --> authDetected: accept("a")

detectingShortScheme --> detectingShortScheme: accept_alphabet

@enduml